### ISSUE TITLE
`divsufsort` useful for `bsdiff`. (Not an issue, just a note.)

### ISSUE THREAD

**Issue by FrankReh** [fasterthanlime/stringsearch#2]
Today I learned about the `bsdiff` and `bspatch`, by Colin Percival. His description is in his https://www.daemonology.net/papers/bsdiff.pdf.

He has an old page that summarizes how it's been useful for various OS distributions [here](https://www.daemonology.net/bsdiff/) and here's a [man page](https://manpages.ubuntu.com/manpages/xenial/en/man1/bsdiff.1.html).

There were some Rust ports some time ago. I picked up [bsdiff-rs](https://github.com/space-wizards/bsdiff-rs).

I found the `bsdiff` inventor/author had become an important contributor to FreeBSD and wondered how his `bsdiff` was used by FreeBSD now. Turns out around 2016, they swapped out an initial call to a hand written `qsufsort` with the Google developed `divsufsort` claiming it was much faster.

Found your port of the library to rust, dropped it into a local `bsdiff-rs` and can confirm it is much much faster. On 4MB rust binaries I tested, `bsdiff` times dropped from 1.1s to 0.3s. Same binary source difference algorithm, just a different way to create the suffix array that it uses. Amazing.

Thanks for the hand port and all that fuzz testing!

**Comment by FrankReh** [comment]
Nothing to complete. Just wanted to ping you and let you know how well this port was working in a related project - years after you last touched it.

**Comment by fasterthanlime** [comment]
> Nothing to complete. Just wanted to ping you and let you know how well this port was working in a related project - years after you last touched it.

Thanks! I'm really happy to hear about it :) I did spend a lot of (paid!) time working on this back then - and used it in https://crates.io/crates/bidiff + https://crates.io/crates/bipatch

**Comment by FrankReh** [comment]
Thank you for pointing me (and future readers) to that crate. I wasn't aware of it. Funny you built this crate for the express purpose I used it for yesterday. The work in your crates is orders of magnitude more thorough and interesting of course. (Thought I was done yesterday but `bidiff` is another vista now.)

The addition of the 'bic' tool was very nice. It was easy to add a bzip2 option. And very interesting to see how the search space could be partitioned for `rayon`.
